# =====================================================
# DOCKER COMPOSE - NESTJS + NGINX FRONT API
# =====================================================
# Stack:
# - NestJS API
# - Nginx reverse proxy
# =====================================================

name: nestjs-incorr

x-nginx-image: &nginx-image nginx:1.29.0-alpine@sha256:d67ea0d64d518b1bb04acde3b00f722ac3e9764b3209a9b0a98924ba35e4b779

networks:
  bloomn-etword:
    external: true


services:

# =====================================================
# NESTJS BACKEND APPLICATION
# =====================================================
  nest-app:
    build: .
    container_name: ${APP_NAME}_API
    restart: always

    ports:
      - "3000:3000"

    environment:
      # MongoDB connection string (via mongos router)
      - MONGO_URI=mongodb://${MONGO_ADMIN_CONFIG_SERVER}:${MONGO_PASSWORD_CONFIG_SERVER}@mongos-router-dn:27017,mongos-router-hn:27017,mongos-router-sg:27017/admin?authSource=admin

    working_dir: /var/www/app

    volumes:
      # Source code bind mount (dev-friendly)
      - ./app:/var/www/app

    env_file:
      - .env

    networks:
      - bloomn-etword


# =====================================================
# NGINX REVERSE PROXY
# =====================================================
  nginx:
    image: *nginx-image
    container_name: ${APP_NAME}_nginx_fAPI
    restart: always

    ports:
      - "80:80"

    volumes:
      # Nginx configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    env_file:
      - .env

    depends_on:
      - nest-app

    networks:
      - bloomn-etword
