server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA hoặc frontend routing
    location / {
        try_files $uri $uri/ =404;
    }

    # Cache static assets
    location ~* \.(css|js|jpg|jpeg|png|gif|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    # Optional: upload size (TinyMCE upload nếu có backend sau này)
    client_max_body_size 50M;
}
