version: "3.9"

networks:
  nest-cluster:
    driver: bridge

services:

  # =========================
  # KEYFILE GENERATOR
  # =========================
  keygen:
    container_name: ${APP_NAME}_keygen
    image: mongo:7
    volumes:
      - ./keyfile:/keyfile
      - ./init/keygen:/keygen
    entrypoint: ["bash", "/keygen/create-keyfile.sh"]

  # =========================
  # CONFIG SERVERS (3 nodes)
  # =========================
  config-sv-primary:
    container_name: ${APP_NAME}_config-sv-primary
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - ./keyfile:/etc
      - ./init/init-config-sv/init-config-sv-primary.js:/init/init.js:ro
      - ./data/config-sv/config-sv-primary:/data/db
    env_file:
      - .env
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet cfgRS --bind_ip_all --configsvr --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for MongoDB startup...'
      while ! mongosh --quiet --host config-sv-primary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host config-sv-assistant:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host config-sv-secretary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'MongoDB is ready'
      mongosh --host config-sv-primary:27017 /init/init.js
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet cfgRS --bind_ip_all --configsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  config-sv-assistant:
    container_name: ${APP_NAME}_config-sv-assistant
    image: mongo:7
    ports:
      - "27019:27017"
    volumes:
      - ./keyfile:/etc
      - ./init/init-config-sv/init-config-sv-assistant.js:/init/init.js:ro
      - ./data/config-sv/config-sv-assistant:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet cfgRS --bind_ip_all --configsvr --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for MongoDB startup...'
      while ! mongosh --quiet --host config-sv-assistant:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'MongoDB is ready'
      mongosh --host config-sv-assistant:27017 /init/init.js
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_CONFIG_SV}:${MONGO_PASSWORD_CONFIG_SV}@config-sv-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet cfgRS --bind_ip_all --configsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  config-sv-secretary:
    container_name: ${APP_NAME}_config-sv-secretary
    image: mongo:7
    ports:
      - "27020:27017"
    volumes:
      - ./keyfile:/etc
      - ./init/init-config-sv/init-config-sv-secretary.js:/init/init.js:ro
      - ./data/config-sv/config-sv-secretary:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_CONFIG_SV}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD_CONFIG_SV}
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet cfgRS --bind_ip_all --configsvr --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for MongoDB startup...'
      while ! mongosh --quiet --host config-sv-secretary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'MongoDB is ready'
      mongosh --host config-sv-secretary:27017 /init/init.js
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_CONFIG_SV}:${MONGO_PASSWORD_CONFIG_SV}@config-sv-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet cfgRS --bind_ip_all --configsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  # =========================
  # SHARD DN
  # =========================
  shard-dn-primary:
    container_name: ${APP_NAME}_shard-dn-primary
    image: mongo:7
    ports:
      - "27021:27017"
    volumes:
      - ./keyfile:/etc
      - ./init/init-shard-dn.js:/init/init.js:ro
      - ./data/sharding/shard-dn-primary:/data/db
    env_file:
      - .env
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet dnRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for MongoDB startup...'
      while ! mongosh --quiet --host shard-dn-primary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host shard-dn-assistant:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host shard-dn-secretary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'MongoDB is ready'
      mongosh --host shard-dn-primary:27017 /init/init.js
      kill -15 $(pidof mongod) 
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet dnRS --bind_ip_all --shardsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  shard-dn-assistant:
    container_name: ${APP_NAME}_shard-dn-assistant
    image: mongo:7
    ports:
      - "27022:27017"
    volumes:
      - ./keyfile:/etc
      - ./data/sharding/shard-dn-assistant:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet dnRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for replica set initialization...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_DN}:${MONGO_PASSWORD_SHARD_DN}@shard-dn-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      echo 'Replica set initialized'
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet dnRS --bind_ip_all --port 27017 --shardsvr --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  shard-dn-secretary:
    container_name: ${APP_NAME}_shard-dn-secretary
    image: mongo:7
    ports:
      - "27023:27017"
    volumes:
      - ./keyfile:/etc
      - ./data/sharding/shard-dn-secretary:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet dnRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for replica set initialization...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_DN}:${MONGO_PASSWORD_SHARD_DN}@shard-dn-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      echo 'Replica set initialized'
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet dnRS --bind_ip_all --port 27017 --shardsvr --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  # =========================
  # SHARD HN
  # =========================
  shard-hn-primary:
    container_name: ${APP_NAME}_shard-hn-primary
    image: mongo:7
    ports:
      - "27024:27017"
    volumes:
      - ./keyfile:/etc
      - ./init/init-shard-hn.js:/init/init.js:ro
      - ./data/sharding/shard-hn-primary:/data/db
    env_file:
      - .env
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet hnRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for MongoDB startup...'
      while ! mongosh --quiet --host shard-hn-primary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host shard-hn-assistant:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host shard-hn-secretary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'MongoDB is ready'
      mongosh --host shard-hn-primary:27017 /init/init.js
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet hnRS --bind_ip_all --shardsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  shard-hn-assistant:
    container_name: ${APP_NAME}_shard-hn-assistant
    image: mongo:7
    ports:
      - "27025:27017"
    volumes:
      - ./keyfile:/etc
      - ./data/sharding/shard-hn-assistant:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet hnRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for replica set initialization...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_HN}:${MONGO_PASSWORD_SHARD_HN}@shard-hn-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      echo 'Replica set initialized'
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet hnRS --bind_ip_all --port 27017 --shardsvr --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  shard-hn-secretary:
    container_name: ${APP_NAME}_shard-hn-secretary
    image: mongo:7
    ports:
      - "27026:27017"
    volumes:
      - ./keyfile:/etc
      - ./data/sharding/shard-hn-secretary:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet hnRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for replica set initialization...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_HN}:${MONGO_PASSWORD_SHARD_HN}@shard-hn-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      echo 'Replica set initialized'
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet hnRS --bind_ip_all --port 27017 --shardsvr --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  # =========================
  # SHARD SG
  # =========================
  shard-sg-primary:
    container_name: ${APP_NAME}_shard-sg-primary
    image: mongo:7
    ports:
      - "27027:27017"
    volumes:
      - ./keyfile:/etc
      - ./init/init-shard-sg.js:/init/init.js:ro
      - ./data/sharding/shard-sg-primary:/data/db
    env_file:
      - .env
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet sgRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for MongoDB startup...'
      while ! mongosh --quiet --host shard-sg-primary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host shard-sg-assistant:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      while ! mongosh --quiet --host shard-sg-secretary:27017 --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'MongoDB is ready'
      mongosh --host shard-sg-primary:27017 /init/init.js
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet sgRS --bind_ip_all --shardsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  shard-sg-assistant:
    container_name: ${APP_NAME}_shard-sg-assistant
    image: mongo:7
    ports:
      - "27028:27017"
    volumes:
      - ./keyfile:/etc
      - ./data/sharding/shard-sg-assistant:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet sgRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for replica set initialization...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_SG}:${MONGO_PASSWORD_SHARD_SG}@shard-sg-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      echo 'Replica set initialized'
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet sgRS --bind_ip_all --port 27017 --shardsvr --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  shard-sg-secretary:
    container_name: ${APP_NAME}_shard-sg-secretary
    image: mongo:7
    ports:
      - "27029:27017"
    volumes:
      - ./keyfile:/etc
      - ./data/sharding/shard-sg-secretary:/data/db
    command: |
      bash -c "
      until [ -f /etc/mongo-keyfile ]; do
        echo 'Waiting for mongo-keyfile...'
        sleep 1
      done
      mongod --replSet sgRS --bind_ip_all --port 27017 --fork --logpath /tmp/mongod.log
      echo 'Waiting for replica set initialization...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_SG}:${MONGO_PASSWORD_SHARD_SG}@shard-sg-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 40
      done
      echo 'Replica set initialized'
      kill -15 $(pidof mongod)
      while pidof mongod > /dev/null; do
        sleep 1
      done
      exec mongod --replSet sgRS --bind_ip_all --shardsvr --port 27017 --auth --setParameter enableLocalhostAuthBypass=0 --keyFile /etc/mongo-keyfile
      "
    networks:
      - nest-cluster

  # =========================
  # MONGOS ROUTER
  # =========================
  mongo-router:
    container_name: ${APP_NAME}_mongo-router
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./keyfile:/etc
      - ./mongo/cluster.js:/mongo/cluster.js:ro
    command: |
      bash -c "
      echo 'Waiting for replica set initialization...'

      echo '⏳ Waiting for CONFIG-SERVER (cfgRS)...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_CONFIG_SV}:${MONGO_PASSWORD_CONFIG_SV}@config-sv-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_CONFIG_SV}:${MONGO_PASSWORD_CONFIG_SV}@config-sv-assistant:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_CONFIG_SV}:${MONGO_PASSWORD_CONFIG_SV}@config-sv-secretary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo '✅ CONFIG-SERVER READY'

      echo '⏳ Waiting for SHARD-DN (dnRS)...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_DN}:${MONGO_PASSWORD_SHARD_DN}@shard-dn-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_DN}:${MONGO_PASSWORD_SHARD_DN}@shard-dn-assistant:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_DN}:${MONGO_PASSWORD_SHARD_DN}@shard-dn-secretary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo '✅ SHARD-DN READY'

      echo '⏳ Waiting for SHARD-HN (hnRS)...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_HN}:${MONGO_PASSWORD_SHARD_HN}@shard-hn-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_HN}:${MONGO_PASSWORD_SHARD_HN}@shard-hn-assistant:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_HN}:${MONGO_PASSWORD_SHARD_HN}@shard-hn-secretary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo '✅ SHARD-HN READY'

      echo '⏳ Waiting for SHARD-SG (sgRS)...'
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_SG}:${MONGO_PASSWORD_SHARD_SG}@shard-sg-primary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_SG}:${MONGO_PASSWORD_SHARD_SG}@shard-sg-assistant:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      until mongosh --quiet 'mongodb://${MONGO_ADMIN_SHARD_SG}:${MONGO_PASSWORD_SHARD_SG}@shard-sg-secretary:27017/admin' --eval 'rs.status().ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo '✅ SHARD-SG READY'

      echo '🎉 ALL REPLICA SETS INITIALIZED'
      mongos --configdb cfgRS/config-sv-primary:27017,config-sv-assistant:27017,config-sv-secretary:27017 --bind_ip_all --keyFile /etc/mongo-keyfile --fork --logpath /tmp/mongos.log
      echo 'Waiting for mongos startup...'
      until mongosh --quiet --host mongo-router --port 27017 -u ${MONGO_ADMIN_CONFIG_SV} -p ${MONGO_PASSWORD_CONFIG_SV} --authenticationDatabase admin --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do
        sleep 1
      done
      echo 'mongos is ready'
      mongosh --host mongo-router --port 27017 -u ${MONGO_ADMIN_CONFIG_SV} -p ${MONGO_PASSWORD_CONFIG_SV} --authenticationDatabase admin /mongo/cluster.js && tail -f /tmp/mongos.log
      "
    networks:
      - nest-cluster

  # =========================
  # MONGO EXPRESS
  # =========================
  mongo-express:
    container_name: ${APP_NAME}_mongo-express
    image: mongo-express
    depends_on:
      - mongo-router
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${EXPRESS_ADMIN}:${EXPRESS_PASSWORD}@mongo-router:27017/admin?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_ADMIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
    command: |
      bash -c "
      echo 'Waiting for mongos startup...'
      until nc -z mongo-router 27017; do
        sleep 1
      done
      echo 'mongos is ready'
      /sbin/tini -- node app
      "
    networks:
      - nest-cluster
