version: "3.9"

networks:
  nest-cluster:
    driver: bridge

services:
  app:
    build: .
    container_name: ${APP_NAME}_BE
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://${MONGO_ADMIN_CONFIG_SV}:${MONGO_PASSWORD_CONFIG_SV}@mongo-router:27017/nestdb?authSource=admin
    volumes:
      - ./app:/var/www/app
    networks:
      - nest-cluster

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nest-cluster
